import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ClientMuiNavbar from "./components/ClientMuiNavbar";
import ClientFooter from "./components/ClientFooter";
import ClientMuiProvider from "./components/ClientMuiProvider";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}
      >
        <AuthProvider>
          <ClientMuiProvider>
            <ClientMuiNavbar />

            {children}

            <ClientFooter />
          </ClientMuiProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
