import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full border-b border-gray-200 dark:border-zinc-800">
          <div className="mx-auto max-w-3xl px-6 py-4 flex items-center justify-between">
            <div className="text-sm font-semibold">Spark</div>
            <nav className="flex gap-4">
              <Link href="/" className="text-sm font-medium text-zinc-900 dark:text-zinc-100">
                Home
              </Link>
              <Link href="/about" className="text-sm font-medium text-zinc-900 dark:text-zinc-100">
                About
              </Link>
            </nav>
          </div>
        </header>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
